/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_airkv_RWDB */

#ifndef _Included_site_ycsb_db_airkv_RWDB
#define _Included_site_ycsb_db_airkv_RWDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_airkv_RWDB
 * Method:    newRWDB
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_site_ycsb_db_airkv_RWDB_newRWDB
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     site_ycsb_db_airkv_RWDB
 * Method:    open
 * Signature: ([BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_airkv_RWDB_open
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     site_ycsb_db_airkv_RWDB
 * Method:    close
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_airkv_RWDB_close
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     site_ycsb_db_airkv_RWDB
 * Method:    put
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_airkv_RWDB_put
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     site_ycsb_db_airkv_RWDB
 * Method:    get
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_site_ycsb_db_airkv_RWDB_get
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
