name: Rust CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  airkv-build:
    runs-on: ubuntu-latest
    env:
       working-directory: ./airkv
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.working-directory}} 
    - name: Launch server
      run: cargo run --bin fake_store_server &
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{env.working-directory}} 
