name: Interface Check

on: push

jobs: 
  python_rust_interface:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./demo/test
        run: |
          cargo build
          cp ../../target/debug/libairindex.dylib .
          mv libairindex.dylib airindex.so
      - name: Run Tests
        working-directory: ./demo/test
        run: python3 test.py
