name: Interface Check

on: push

jobs: 
  python_rust_interface:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cargo build
          cp ./target/debug/libairindex.dylib ./demo/test
          mv ./demo/test/libairindex.dylib ./demo/test/airindex.so
      - name: Run Tests
        run: python3 ./demo/test.py
